### ISSUE TITLE
Windows VM names longer than 15 characters passing validation

### ISSUE THREAD

**Issue by d-r-tet** [mspnp/AzureNamingTool#33] opened 2023-10-24 02:52 UTC
**Describe the bug**
When generating a name for _Compute/VirtualMachines - Windows (vm)_, the max length does not appear to be validated, which allows names longer than 15 characters to be generated successfully.

**To Reproduce**
1. Go to 'Generate'
2. Click on 'Type to search resource types'
3. Scroll down to 'Compute/virtualMachines - Windows (vm)'
4. Fill out parameters and pad out instance field to make it longer than 15 characters
5. Click Generate

**Expected behavior**
Validation fails and error is returned indicating name is too long.

**Screenshots**
![image](https://github.com/mspnp/AzureNamingTool/assets/67937874/dc3b33a4-0fb2-41af-975b-c14e75297068)

**Installation Method**
Azure Web App Using GitHub Action

**Additional context**

**Comment by BryanSoltis** [comment] 2023-10-26 14:44
Thank you for your feedback The issue is related to the auto-complete field on the Generate page and identifying the correct resource type to validate. This will be fixed int he next release.

- Bryabn

**Closed** 2023-10-30 15:00 UTC
Labels: bug
