### ISSUE TITLE
Unable to download artifact(s): Artifact not found for name: .net-app

### ISSUE THREAD

**Issue by MattDyson85** [mspnp/AzureNamingTool#117] opened 2024-11-05 22:44 UTC
**Tool version**
Latest Main Branch Deployment 

**Describe the bug**
When trying to deploy to app services we are see the below error 

_**Run actions/download-artifact@v4.1.7
  with:
    name: .net-app
    merge-multiple: false
    repository: ######/AzureNamingTool
    run-id: 1169[2](https://github.com/####/AzureNamingTool/actions/runs/11692473815/job/32561972233#step:2:2)473815
  env:
    AZURE_WEBAPP_PACKAGE_PATH: .
    DOTNET_VERSION: 8.0.x
Downloading single artifact
Error: Unable to download artifact(s): Artifact not found for name: .net-app
        Please ensure that your artifact is not expired and the artifact was uploaded using a compatible version of toolkit/upload-artifact.
        For more information, visit the GitHub Artifacts FAQ: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md**_

Unable to download artifact(s): Artifact not found for name: .net-app

**To Reproduce**
1. Go to actions
2. Click on "Azure Naming Tool - Build and deploy to an Azure Web App"
3. Run workflow

**Expected behavior**
AzureNamingTool Deployed to app services 

**Screenshots**
![image](https://github.com/user-attachments/assets/6fd7cccc-dc99-4b61-af95-7fbf8e3dc0e4)

**Comment by mrwalters1988** [comment] 2024-11-18 06:50
I'm having this same issue.

**Comment by mrwalters1988** [comment] 2024-11-18 06:58
@MattDyson85  this is a duplicate of https://github.com/mspnp/AzureNamingTool/issues/115. If you update your deploy yml 
`actions/upload-artifact@v3`
 to 
 `actions/upload-artifact@v4`
 it should work for you.

**Comment by BryanSoltis** [comment] 2024-11-19 15:26
This change has been merged to the main branch, Please pull the latest version and it should build/deploy properly.

- Bryan

**Closed** 2024-11-19 15:28 UTC
